### ISSUE TITLE
Auction bug bp didnt appear after selling !

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#153] opened 2022-07-09 21:05 UTC
**Describe the bug**
after i posted "Hunter" Streamliner (Blueprint) , i couldnt find in the Auction , no one can see it unless u type in searching box in auction then you can see and buy it ,,,,

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment] 2022-07-09 23:18
Can't reproduce.

**Comment by StarfishPrime-1** [comment] 2022-07-11 02:11
I purchased this bp from CUrvaSudMilano.  It was only searchable.  did not display in TC.  New bp's in the game would be searchable before they were implemented not that it matters

**Comment by ToxicSSJ** [comment] 2022-07-11 13:57
Is too probably that this bug was caused by the ID issue. Check #103.

**Comment by ToxicSSJ** [comment] 2022-07-13 04:37
Resolved in `V2022.1207a.closed-alpha` version.

**Closed by ToxicSSJ** 2022-07-13 04:37 UTC
Labels: bug
