### ISSUE TITLE
I keep getting Taskmaster blueprint

### ISSUE THREAD

**Issue by ABanC1001** [SuperGO2/supergo2-issues#65] opened 2022-06-30 21:00 UTC
I was waiting for the 2nd laser blueprint but I just got taskmaster, I have the blueprint already investigated but I have 5 more :
![eISE9lJ](https://user-images.githubusercontent.com/108493836/176777551-ca6dfc4b-0510-42ec-8fd9-b9b7b5b764fd.png)
/

**Comment by ABanC1001** [comment] 2022-06-30 21:04
And that's not all, I cant use the laser weapons because I cant get the Magneto Pulsar

**Comment by ToxicSSJ** [comment] 2022-07-04 01:43
This is duplicate of #56.

**Closed by ToxicSSJ** 2022-07-04 01:43 UTC
Labels: bug
