### ISSUE TITLE
Only 5 slots available in the Trading Center

### ISSUE THREAD

**Issue by StarfishPrime-1** [SuperGO2/supergo2-issues#25] opened 2022-03-27 20:10 UTC
Unique Title: 5 slots available in the TC
Description: I only have 5 slots available in the TC when "selling"
How to reproduce:  Attempt to sell more then 5 items ,etc. should it not be 4 pages? 20?

**Comment by ToxicSSJ** [comment] 2022-03-30 05:12
This is a duplicate of #14.

**Closed by ToxicSSJ** 2022-03-30 05:12 UTC
Labels: bug, duplicate
