### ISSUE TITLE
Can't bind Bionic chips to Commander

### ISSUE THREAD

**Issue by RockandTroll** [SuperGO2/supergo2-issues#134] opened 2022-07-08 05:28 UTC
**Describe the bug**
Unable to bind Bionic Chips to commanders

**To Reproduce**
1. Create some bionic chips
2. Try to bind chip to commander

**Expected behaviour**
Chips should bind to commander, when trying to do this, the chip doesn't bind, clicking "Bind" instead just locks and unlocks the chip

**Comment by Tuni67** [comment] 2022-07-08 12:22
@ToxicSSJ i think the problem is that the commanders already come with biochips

![biochip](https://user-images.githubusercontent.com/108492773/177991210-be22e340-7426-40a1-a6e1-573a09ab3f3c.JPG)

**Comment by ToxicSSJ** [comment] 2022-07-09 09:31
The problem is that this feature is not already done. You can generate bionic chips but they don't work and you can't bind them to commanders.

**Comment by ToxicSSJ** [comment] 2022-07-27 18:06
Resolved in `V2022.2707a.closed-alpha` version.

**Closed by ToxicSSJ** 2022-07-27 18:06 UTC
Labels: bug
