### ISSUE TITLE
My ships go away after sell another ship

### ISSUE THREAD

**Issue by Zacmadness** [SuperGO2/supergo2-issues#66] opened 2022-06-30 22:27 UTC
#bug 
How to produce: In market I put I put first the price to 10 after I close the market and open it again, in sell I just put the amount of wike to 1 because the price was already put, then pushing sell button doesn't work I push it like 8-10 times, I close the market and open it again putting the price and the amount at the same time without close (1 wike for 10 gold) and sell it, but after do that all my ships disappear, I started again the game and it still disappear, just appear 0 wike in my inventory 
![Screenshot_2022-06-30-18-25-49-717_com cloudmosa puffinFree](https://user-images.githubusercontent.com/108496089/176788965-bcf4415f-f3f0-44c9-9269-99fd00572563.jpg)

**Comment by ABanC1001** [comment] 2022-07-01 01:54
The same just happened to me, I though it was a visual bug but after reloading the game it wasn't in my ship inventory

**Comment by ToxicSSJ** [comment] 2022-07-04 01:42
This is duplicate of #56.

**Comment by ToxicSSJ** [comment] 2022-07-23 18:42
Resolved in `V2022.2307a.closed-alpha` version.

**Closed by ToxicSSJ** 2022-07-23 18:42 UTC
Labels: bug
