### ISSUE TITLE
The quest Military ranks I can not be completed

### ISSUE THREAD

**Issue by Kariuzz** [SuperGO2/supergo2-issues#222] opened 2022-07-24 16:42 UTC
**Describe the bug**
When you obtain a 3* card or use this the quest not be completed

**To Reproduce**
1. Go to 'Bag'
2. Click on 'Use the Commander with three stars'
3. Scroll down to 'Quests'

**Expected behavior**
The quests will be completed when you use a 3* commander card.

**Screenshots**
![Mission](https://user-images.githubusercontent.com/109613356/180657371-bf3ade46-987e-410e-99a2-d5bf836f803c.png)
![Card](https://user-images.githubusercontent.com/109613356/180657428-fc5b9ccb-24f4-4305-9f3c-e849349d9088.png)
**Additional context**
I'd used this panis and the quest will not be completed,

**Comment by irtusb** [comment] 2022-07-25 13:52
duplicate of #207

**Comment by spectuu** [comment] 2022-08-01 03:42
Done°

**Comment by ToxicSSJ** [comment] 2022-08-08 08:46
Resolved in `V2022.0808a.closed-alpha` version.

**Closed by ToxicSSJ** 2022-08-08 08:46 UTC
Labels: bug
