### ISSUE TITLE
Inventory Viewing 

### ISSUE THREAD

**Issue by DevTruce** [SuperGO2/supergo2-issues#35] opened 2022-03-31 02:45 UTC
Description: when you try to view you inventory select categories, it does not function correctly

How to reproduce: try and view your inventory select categories 

Expected behavior: you should be able to view each tab once you click the selected category icon

Video 1: https://jmp.sh/9GWyUae

**Comment by ToxicSSJ** [comment] 2022-05-13 01:40
I can't reproduce this bug

**Comment by ToxicSSJ** [comment] 2022-05-14 14:59
Resolved in `V2022.514b.beta-dev` version.

**Closed** 2022-09-27 05:36 UTC
Labels: bug
