### ISSUE TITLE
Upgrading Some he3  collectors to lvl 6 will increase gold instead of he3

### ISSUE THREAD

**Issue by calacavenezolana** [SuperGO2/supergo2-issues#90] opened 2022-07-04 18:13 UTC
I did reset to the game twice, and the value of the he3 was designed to gold. after lvl 7 everything goes good

**Comment by ToxicSSJ** [comment] 2022-07-05 21:30
Can't reproduce it.

**Comment by ToxicSSJ** [comment] 2022-07-08 05:05
Resolved in `V2022.0807a.closed-alpha` version.

**Closed by ToxicSSJ** 2022-07-08 05:05 UTC
Labels: bug
