### ISSUE TITLE
Corps Events MIssing

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#269] opened 2022-08-14 00:06 UTC
**Describe the bug**
No working corps events 

**To Reproduce**
Look in corps events

**Expected behavior**
list of all events in corps 

**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment] 2022-09-27 05:37
Duplicate of #47.

**Closed by ToxicSSJ** 2022-09-27 05:37 UTC
Labels: bug
