### ISSUE TITLE
side quest friendly faces 1 unclaimable 

### ISSUE THREAD

**Issue by CUrvaSudMilano** [SuperGO2/supergo2-issues#101] opened 2022-07-05 13:52 UTC
**Describe the bug**
side quest friendly faces 1 should be claimed after adding 2 friends , i have 10 friends but still unclaimable 

**To Reproduce**
1. Go to tutorial 
2. Click on Enter Quest
3. Scroll down to side quest then find friendly faces 1
4. See error you cant claim the prize even its done 

**Expected behavior**
should be claimable after adding 2 friends 

**Screenshots**
I
![friendly faces1](https://user-images.githubusercontent.com/108695969/177343758-e2cf52f2-0235-480a-a896-186233949c24.png)

**Comment by ToxicSSJ** [comment] 2022-07-05 15:11
This is duplicate of #96.

**Closed by ToxicSSJ** 2022-07-05 15:11 UTC
Labels: bug
