### ISSUE TITLE
When leaving corps, things in corps bag lost

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#305] opened 2022-08-22 09:35 UTC
**Describe the bug**
When leaving corps, things in corps bag lost
**To Reproduce**
join corps
put items in corps bag
leave corps
notice your items gone
**Expected behavior**
receive a mail with all your items in it
**Screenshots**

**Additional context**

**Comment by ToxicSSJ** [comment] 2022-08-23 20:04
Duplicate of #252.

**Closed by ToxicSSJ** 2022-08-23 20:04 UTC
Labels: bug
