### ISSUE TITLE
Truce Cards not working

### ISSUE THREAD

**Issue by Gloster173** [SuperGO2/supergo2-issues#369] opened 2022-09-26 01:14 UTC
**Describe the bug**
Truce Cards sometimes can be used and not apply truce status to planets. This occurs only when fleets are in an instance.
**To Reproduce**
1. Send fleets to any instance
2. Apply truce Card in bag
3. Truce card will be used, but account will not be truced.

**Expected behavior**
Truce Cards to apply when fleets are in instances.

**Comment by deltaflyer97** [comment] 2022-09-26 09:46
bought two advance truce cards both have failed to work and disappeared out of my bag

**Comment by ToxicSSJ** [comment] 2022-09-27 05:26
Duplicate of #359.

**Closed by ToxicSSJ** 2022-09-27 05:26 UTC
Labels: bug
