### ISSUE TITLE
Cant visit Starbase from Corpmembers

### ISSUE THREAD

**Issue by Tuni67** [SuperGO2/supergo2-issues#95] opened 2022-07-05 07:30 UTC
**Describe the bug**
You cant visit the starbase of a corp member if he isnt in your friendlist

**To Reproduce**
Just try to visit the starbase of a corp member who isnt on your friendlist

**Expected behavior**
You should visit the starbase

**Comment by ToxicSSJ** [comment] 2022-07-07 00:04
This is duplicate of #42.

**Closed by ToxicSSJ** 2022-07-07 00:04 UTC
Labels: bug
