### ISSUE TITLE
Ships vanishing when fleeting

### ISSUE THREAD

**Issue by Warner231936** [SuperGO2/supergo2-issues#354] opened 2022-09-09 18:04 UTC
**Describe the bug**
Ships vanishing when fleeting

**To Reproduce**
fleet ships up
notice ships missing you had before

**Expected behavior**
ships to not vanish and be gone 

**Screenshots**

**Additional context**

**Comment by Warner231936** [comment] 2022-09-09 18:12
further testing shows this seems to mostly happen when using the "fleet save/load" function, and even more common when you try to load a fleet that uses more ships then you have left of a certain build. i took notice that when you do load a save with more ships then you currently have, and you save the fleet, the amounts of ships will show a - number   like -688 and then when you close out of that, its like it keeps the - number as a "true value" because when doing the math, the - number is always the amount of ships that have been "lost"

**Comment by skyprime17** [comment] 2022-09-26 23:02
duplicate of #344

**Comment by ToxicSSJ** [comment] 2022-09-27 05:11
Duplicate of #344.

**Closed by ToxicSSJ** 2022-09-27 05:11 UTC
Labels: bug
