### ISSUE TITLE
Commander Stuck in instance

### ISSUE THREAD

**Issue by Hammercrow** [SuperGO2/supergo2-issues#192] opened 2022-07-18 14:03 UTC
**Describe the bug**
Commander gets stuck in instance after losing the instance.

**To Reproduce**
1. go to normal instances
2. start a normal instance you know you will lose
3. wait for instance to finish

**Expected behavior**
some fleets die, i had one get stuck in "in battle"

**Screenshots**
![image](https://user-images.githubusercontent.com/54480164/179528726-2f636da8-9083-400f-ae2b-bc8fbdd93670.png)

**Additional context**
N/A

**Comment by irtusb** [comment] 2022-07-18 14:34
duplicate of #188 but this one has more info

**Comment by ToxicSSJ** [comment] 2022-07-20 23:50
Resolved in `V2022.2007a.closed-alpha` version.

**Closed by ToxicSSJ** 2022-07-20 23:50 UTC
Labels: bug
