### ISSUE TITLE
Wheel bug #1

### ISSUE THREAD

**Issue by Accone** [SuperGO2/supergo2-issues#71] opened 2022-07-01 09:28 UTC
Description: Uni spark gives players 4,2 billion gold what you cant use and after that the server resets your gold

**Comment by Accone** [comment] 2022-07-01 09:30
(only like 75% sure it was uni spark)

**Comment by Accone** [comment] 2022-07-01 10:15
Landed on uni spark again, and didnt get gold = it happens randomly

**Comment by ToxicSSJ** [comment] 2022-07-04 01:44
This is duplicate of #63.

**Closed by ToxicSSJ** 2022-07-04 01:44 UTC
Labels: bug
