### ISSUE TITLE
Corps member list does not show second page

### ISSUE THREAD

**Issue by irtusb** [SuperGO2/supergo2-issues#104] opened 2022-07-05 21:36 UTC
Description: in a corp with more than 10 members, the member list going to the second page shows an empty list

how to:
. in galaxy view click a player which belongs to a corp
. click the corps name
. go to second page using the arrows at the bottom of window
. the list is empty, but you can go to the first page, i.e. HUD is not stuck, and data from the first page remains correct

expected: to show the remaining members

**Comment by ToxicSSJ** [comment] 2022-07-06 01:56
This is a duplicate of #97.

**Closed by ToxicSSJ** 2022-07-06 01:56 UTC
Labels: bug
